### ISSUE TITLE
avg bug

### ISSUE THREAD

**Issue by BernhardBaumrock** [BernhardBaumrock/RockTabulator#1]
![avg-bug](https://user-images.githubusercontent.com/8488586/59997346-28137700-965d-11e9-90ca-a391bbe77302.gif)

SUM works as expected.

https://github.com/BernhardBaumrock/FieldtypeRockTabulator/blob/098cd259c33f6d025c9cbc5c33fdaca916acf9db/examples/05-filter-sum-formatters.js#L7

**Comment by mestaritonttu** [comment]
Function in Tabulator: https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/calculation_colums.js#L373

**Comment by BernhardBaumrock** [comment]
Thx, the money formatter also seems buggy...

**Comment by BernhardBaumrock** [comment]
FYI: I've pushed a complete rewrite of RockTabulator and need to try that with the latest version...
