### ISSUE TITLE
Move columns

### ISSUE THREAD

**Issue by BernhardBaumrock** [BernhardBaumrock/RockTabulator#3]
In FieldtypeRockGrid, I noticed moveColumns was used/offered. Tabulator does not have a move method. I guess it might be useful?

@mestaritonttu

**Comment by mestaritonttu** [comment]
Hah, I just noticed that Tabulator 4.3 will have this, it is issue 1754 (not linking as I want to avoid reference spamming the issue)! I must have failed to find it on my first search attempt.

I think we can close.

**Comment by BernhardBaumrock** [comment]
> When will Tabulator 4.3 be available?

Just saw it is scheduled for end of may 2019 ^^
