### ISSUE TITLE
Some translations are missing

### ISSUE THREAD

**Issue by BernhardBaumrock** [BernhardBaumrock/RockTabulator#6]
Maybe someone could help me with those missing translations so that I can continue working on more important stuff? Thx :)

![image](https://user-images.githubusercontent.com/8488586/60018929-e3073900-968c-11e9-95a7-b28253528cc3.png)

**Comment by jmartsch** [comment]
Will do. But which files do I have to modify? All variables in _langs.php seem to be already translated.

**Comment by BernhardBaumrock** [comment]
That's the help that I'd need - don't know where the "page size" is defined ;) "filter column" should just be missing in _langs.php: http://tabulator.info/docs/4.2/localize

**Comment by mestaritonttu** [comment]
> That's the help that I'd need - don't know where the "page size" is defined ;) "filter column" should just be missing in _langs.php: http://tabulator.info/docs/4.2/localize

Here? https://github.com/olifolkerd/tabulator/blob/master/src/js/modules/localize.js#L180

**Comment by BernhardBaumrock** [comment]
lol, I swear it was not there yesterday 😉 🤣 

Thx guys, fixed with 3d6fe399b21e80cae28968935d841aab8b007026
