### ISSUE TITLE
Error: Class 'ProcessWire\RockMarkupSandbox' not found when trying to install RockTabulator Sandbox

### ISSUE THREAD

**Issue by mestaritonttu** [BernhardBaumrock/RockTabulator#8]
Where can I find RockMarkupSandbox? I had already installed FieldtypeRockMarkup and its input field.

**Comment by BernhardBaumrock** [comment]
Please see the DEV branch

**Comment by mestaritonttu** [comment]
Where can I see the DEV branch? I only see master.

Edit: ok, well https://github.com/BernhardBaumrock/FieldtypeRockTabulator/tree/654b7ba87745ae24d85f857a72623fcbcddc1847

**Comment by mestaritonttu** [comment]
All your change does is check, if RockMarkup is installed or not. My problem is not related to that, but RockMarkupSandbox, which does not come with RockMarkup. Perhaps it is some local module that you have not released yet?

Edit: oh, you meant https://github.com/BernhardBaumrock/FieldtypeRockMarkup/tree/dev
Thanks, now it works. It is a bit strange, though, that it said "Install FieldtypeRockMarkup first!" when installing RockTabulator Sandbox even though all the RockMarkup modules were installed.

**Comment by BernhardBaumrock** [comment]
Yes, I'm working on it. I have to add some changes of how data is retrieved. Some changes will come in the next release. I'm not sure why nobody of you guys is watching / using the dedicated repo for testing / developing RockTabulator: https://github.com/BernhardBaumrock/tabulator.test
There you have all the necessary modules in place, some sample data etc...

**Comment by mestaritonttu** [comment]
> I'm not sure why nobody of you guys is watching / using the dedicated repo for testing / developing RockTabulator: https://github.com/BernhardBaumrock/tabulator.test

1. I cloned a setup with my own data
2. I'm slammed with work from day job :)
