### ISSUE TITLE
$this->langs is NULL in getLocale() of InputfieldRockTabulator.module.php

### ISSUE THREAD

**Issue by mestaritonttu** [BernhardBaumrock/RockTabulator#9]
1. Go to RockTabulator Sandbox, open 02-simple-php-data
2. See console/page source

The script block is spammed with PHP notices:

```
<br />
<b>Notice</b>:  Undefined offset: 1 in <b>/srv/site/modules/FieldtypeRockTabulator/InputfieldRockTabulator.module.php</b> on line <b>120</b><br />
<br />
<b>Notice</b>:  Trying to get property 'name' of non-object in <b>/srv/site/modules/FieldtypeRockTabulator/InputfieldRockTabulator.module.php</b> on line <b>121</b><br />
```
This makes the script break with SyntaxError: expected expression, got '>'.

var_dump($this->langs) in the function reveals it to be NULL.

**Comment by BernhardBaumrock** [comment]
Hi @mestaritonttu I'm working on a new version. I have to change how the data is sent to tabulator... At the moment RockTabulator is not working properly.
